### ISSUE TITLE
AI stuck in Reduce Mistake mode in match (0.64.0)

### ISSUE THREAD

**Issue by ironymanvr** [ForFunLabs/ElevenPublicBugsAndAsks#233]
When playing AI in free hit mode, the Reduce Mistake mode works correctly but when in match it seems to be stuck on regardless of the setting on the UI (tick box).

**Comment by carrotstien** [comment]
@ironymanvr  i believe this is fixed, can you confirm when you get a chance?

**Comment by ironymanvr** [comment]
hi - sorry - still the same for me. am on 0.67.0 now and tried starting a match vs easy ai and toggled the reduce mistake mode a number of times and still has no effect.

**Comment by carrotstien** [comment]
fixed
